<?php

namespace DecodesBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findclosed($user)
    {
        $query = $this->getEntityManager()->getRepository('DecodesBundle:Command')
            ->createQueryBuilder('a')
            ->select('a.date, p.price, p.picture, p.name, e.number, e.cost')
            ->join('a.commanddetails','e')
            ->join('e.produit','p')
            ->where('a.confirmation=1')
            ->andWhere('a.client=:user')->setParameter('user', $user)->getQuery()->getResult();
        return $query;
    }
    public function findnew($user)
    {
        $query = $this->getEntityManager()->getRepository('DecodesBundle:Command')
            ->createQueryBuilder('a')
            ->select('e.id, p.price, p.picture, p.name, e.number, e.cost')
            ->join('a.commanddetails','e')
            ->join('e.produit','p')
            ->where('a.confirmation=0')
            ->andWhere('a.client=:user')->setParameter('user', $user)->getQuery()->getResult();
        return $query;

    }
}
