client_index:
    path:     /
    defaults: { _controller: "DecodesBundle:Client:index" }
    methods:  GET

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "DecodesBundle:Client:edit" }
    methods:  [GET, POST]

client_show:
    path:     /{id}/show
    defaults: { _controller: "DecodesBundle:Client:show" }
    methods:  [GET, POST]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "DecodesBundle:Client:delete" }
    methods:  DELETE
